### ISSUE TITLE
Add a spec that verifies that stub models have inheritance check

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-schema#114]
I'm not sure how, but it might help data migration authors if the stub models they create were verified as to whether or not they require the

```ruby
self.inheritance_column = :_type_disabled # disable STI
```

We might be able to do it by creating a separate test as part of https://github.com/ManageIQ/manageiq-schema/blob/3b374e688e1928b31630a9292338e794510c77b3/spec/support/migration_helper.rb#L6-L18

**Comment by bdunne** [comment]
Fixed by: https://github.com/ManageIQ/manageiq-schema/pull/245
