### ISSUE TITLE
Interrupting migration during 20150806211453 leaves DB un-migratable

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-schema#133]
db/migrate/20150806211453_rename_ems_event_table_to_event_stream.rb uses disable_ddl_transaction! for re-entrancy, but it does both data and schema making it non-reentrant.  This is really bad because if someone interrupts the migration during this PR, their database will be in an un-migratable state, because the rename_column will get run, not rolled back, and then is not runnable again.

The proper fix is to split this migration into 3... pre schema, then data, then post schema.  However, we have to deal with any database that have already migrated past this point.

cc @lfu @gtanzillo

**Comment by JPrause** [comment]
@gtanzillo @lfu is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
