### ISSUE TITLE
Add unique index to tags and/or classifications table

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-schema#152]
Label->tag mapping creates tag "entries" on demand during inventory refresh.
This has to be done atomically, as tags don't have an ems_id, they're global.
Without a unique index it's slow (the best solution I had was DB locking on the parent category row).

- `Classification` model has a complicated custom uniqueness validation:
https://github.com/ManageIQ/manageiq/blob/79d25e361d/app/models/classification.rb#L13-L20
  It might be enough to add unique index only on `Tag`, and ensure entry creation always creates the Tag before the Classification?

- Tags from different region can (and will) have same name when replicated to master region.

**Comment by Fryguy** [comment]
@kbrock Thoughts?

**Comment by cben** [comment]
Yeah that might be enough, as it's similar to existing validation only actually guaranteed.
Need to review creation order — is it always Classification-then-Tag?  If a Tag is created first, and then the Classification fails uniqueness, should roll back the Tag.  Or just wrap these in a transaction.
Or can postpone this until your quest to merge Classification & Tag, would become no-brainer then :-)

- [ ] should also amend [tag mapping](https://github.com/ManageIQ/manageiq/blob/hammer-1-rc2/app/models/container_label_tag_mapping/mapper.rb#L112) to catch `ActiveRecord::RecordNotUnique` as well.
- [ ] are there any other places where RecordNotUnique errors would break things?

**Comment by JPrause** [comment]
@miq-bot remove_label stale
