### ISSUE TITLE
remove CINDER storage object

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-schema#186]
Based on discussing with @himdel and @hstastna we found that support for `Storage`  object with `store_type = CINDER` has been removed.

So we need to remove such objects from DB with migration.

I believe that query to determine `what to remove` is
`Storage.where(:store_type => 'CINDER')`
@himdel is it enough ? 

# Links
After discussion  in https://github.com/ManageIQ/manageiq-ui-classic/issues/3742

UI related issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/3743

# Screenshot  

(highlighted is object to remove for example)
![](https://user-images.githubusercontent.com/13417815/38553173-abc74e18-3cbe-11e8-97a0-5237c60a11fe.png)

**Comment by himdel** [comment]
Also swift :)

**Comment by Fryguy** [comment]
@roliveri Can you comment on this?

**Comment by roliveri** [comment]
As far as I know, they both should still be supported. What makes you believe they are not?
Is this just from a "datastore" point of view - storage where VM files reside? Because Cinder and Swift storage objects are still collected.

@jerryk55 @hsong-rh FYI

**Comment by jerryk55** [comment]
I don't believe we do.  I think this is just datastores.  Regardless I'm not sure why we would be removing these.

**Comment by himdel** [comment]
Ok, maybe there's been some confusion here..

"ontap" was supposed to be removed, right?

**Comment by jerryk55** [comment]
Yes "ontap" should be nuked.  I'm not sure why EmsSwift and EmsCinder are dead.  I'll take a look...

**Comment by JPrause** [comment]
@jerryk55 is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
