### ISSUE TITLE
rubocop: Rails/SkipsModelValidations - Avoid using update_all because it skips validations.

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-schema#20]
Need to ignore / change this cop, because in migration update_all is expected.

**Comment by JPrause** [comment]
@Fryguy @carbonin is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by carbonin** [comment]
Looks like this is still valid @JPrause

**Comment by JPrause** [comment]
Thanks @carbonin
