### ISSUE TITLE
db:seed tries to touch a non-existent arbitration_settings table

### ISSUE THREAD

**Issue by Glutexo** [ManageIQ/manageiq-schema#334]
Running _bin/setup_ from a rather old version of the database fails for me. It fails on running `bundle exec rake db:seed` with the following error.

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "arbitration_settings" does not exist
LINE 8:                WHERE a.attrelid = '"arbitration_settings"'::...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
             (SELECT c.collname FROM pg_collation c, pg_type t
               WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation),
                     col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"arbitration_settings"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
```

I see that the _arbitration_settings_ table has been [dropped](https://github.com/ManageIQ/manageiq-schema/blob/5d7dcef9f3ed52ae01a0c152c948528679d1697b/db/migrate/20170418141731_drop_arbitration_tables.rb#L3) in [_20170418141731_](https://github.com/ManageIQ/manageiq-schema/blob/5d7dcef9f3ed52ae01a0c152c948528679d1697b/db/migrate/20170418141731_drop_arbitration_tables.rb). So that might be the cause. Maybe the model still exists and is used by some migration?

**Comment by carbonin** [comment]
Are you sure you're using the correct schema repo tag/sha with the "rather old version"? Can you give some more exact details about the version of manageiq core and schema you're using as well as the last migrated version in the database you're connecting to?

**Comment by Glutexo** [comment]
Oh! Of course I didn’t have the _manageiq_ repo in sync with the _manageiq-schema_ one. It’s been quite some time since I touched ManageIQ. Sorry for the noise.

I can’t still get the _db:seed_ task to complete successfully, now failing with

> Error parsing classes in /Users/stomsa/dev/manageiq/app/models/vm_reconfigure_task.rb:
> KeyError: key not found: s(:@period, ".", s(14, 21))

but that is a different issue. I actually don’t need to spin up the instance any more, so I’d just leave this. If you’re interested in this though, I can create a new issue and try to help with debugging.

(Also ran into another issue when migrating: 
https://github.com/ManageIQ/manageiq/commit/47a5df05d59d5a7160aa1467ba285b1f8644cb87)

**Comment by period** [comment]
i have been summoned
