### ISSUE TITLE
[V2V] Create conversion hosts for appropriately tagged vms

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-schema#354]
Prior to the existence of the `conversion_hosts` table, we were relying on a specific tag on the resource to identify it as a conversion host. Specifically, the `/managed/v2v_transformation_host/true` tag.

So, we should write a migration that looks for resources with that tag that aren't already in the conversion_hosts table, and create a basic conversion_host record for it, along with an associated authentication if the resource (or provider) has one.

**Comment by fdupont-redhat** [comment]
I would also recommend that we check that the conversion host is correctly configured, by running `check_conversion_host_role`.

**Comment by mfeifer** [comment]
@djberg96 is this still relevant?

**Comment by djberg96** [comment]
@mfeifer Hm, I don't think so. I will let @fdupont-redhat open an issue if he thinks it needs to be done.
