### ISSUE TITLE
Migration has a too long of name

### ISSUE THREAD

**Issue by juliancheal** [ManageIQ/manageiq-schema#428]
While trying to build a `manageiq-schema.gem` I got the following error:

```
ERROR:  While executing gem ... (Gem::Package::TooLongFileName)
    File "db/migrate/20141126161823_convert_show_refresh_button_and_load_values_on_init_to_real_columns_for_dialog_fields.rb" has a too long name (should be 100 or less)
```

I think I remember @Fryguy mentioning something about this. Was there a workaround?

**Comment by agrare** [comment]
This migration bit us recently trying to extract the -schema repo from a .tar.gz actually, https://github.com/ManageIQ/manageiq-cross_repo/pull/43

**Comment by Fryguy** [comment]
We can probably just rename it.

**Comment by juliancheal** [comment]
https://github.com/rubygems/rubygems/blob/master/lib/rubygems/package/tar_writer.rb#L311-L333 makes interesting reading.

Just working on a PR, but it's dinner time 🌮

**Comment by djberg96** [comment]
https://github.com/rubygems/rubygems/issues/1376
