### ISSUE TITLE
The `rails generate migration` command should also generate a spec file

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-schema#479]
This woule speed up things a little bit, maybe we should make it just optional.

cc @Fryguy

**Comment by Fryguy** [comment]
I'm not sure about this one, since we only require specs for data migrations, and most migrations are just normal schema migrations.

**Comment by skateman** [comment]
Maybe an optional one?

**Comment by Fryguy** [comment]
I could see an optional argument during generation, yeah.  Do you know how to modify existing Rails generators?

**Comment by skateman** [comment]
Not yet :laughing: will get back to you tomorrow :stuck_out_tongue:

**Comment by kbrock** [comment]
generating a file with an up/down and having the correct name and spec name would be very nice
that is where my time is spent
