### ISSUE TITLE
Fetching the released migrations pollutes the local repo

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-schema#6]
When the migrations lived in ManageIQ proper, fetching a different branch locally was ok, because it was the same repo.  Now that the schema has been separated out, fetching the ManageIQ/manageiq code *into* the ManageIQ/manageiq-schema repo pollutes the repo with the remote branches and tags.  Unfortunately those tags will collide, for example when we cut gaprindashvili-1 on both repos, then try to fetch, you will get duplicate tag names, and I have no idea what will happen.  We need an alternative now.

cc @carbonin

**Comment by carbonin** [comment]
We had a few different versions of this. We used to hit the github API to get the migrations for a particular branch. We could resurrect that, but I think we were afraid of hitting the API rate limiter. Maybe that won't matter now that these specs are not running with every PR to the core repo?
