### ISSUE TITLE
Change rake tasks so that rake spec does everything

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-schema#65]
Unlike other repos, `rake spec` does not run `spec:migrations` but instead only the "other" specs.  We should change the current spec to something like `spec:common` and then `rake spec` will do both.  (The `rake` default would then just be calling `rake spec`)

**Comment by Fryguy** [comment]
cc @sergio-ocon

**Comment by sergio-ocon** [comment]
👍
